### ISSUE TITLE
Sample config files missing

### ISSUE THREAD

**Issue by marians** [TykTechnologies/tyk-gateway-docker#10]
In the docker repo description at https://hub.docker.com/r/tykio/tyk-gateway/ there is this info:

> Run a standalone Tyk Gateway with your (modified) tyk.conf (see sample configs in our docker github repository):

I'm expecting to find the config files here in the repo, but they are not here.

**Comment by marians** [comment]
OK, as with #9, this can (only) be found in a non-default branch.

https://github.com/TykTechnologies/tyk-gateway-docker/blob/version/v2.3.7/tyk.standalone.conf

**Comment by marians** [comment]
I strongly recommend a README for this repo which points to the branches.

**Comment by mvdan** [comment]
Let's keep the discussion about the repo structure there. Feel free to rename that issue to better reflect it.

**Comment by marians** [comment]
It's your repo. Feel free to close what you consider a duplicate.

**Comment by mvdan** [comment]
I would - I don't have the rights to, though :)
