### ISSUE TITLE
docker-compose image changed?

### ISSUE THREAD

**Issue by dylanmcreynolds** [TykTechnologies/tyk-gateway-docker#60]
Trying to get the demo to work locally, it appears that the image tag pointing to docker.tyk.io does not work. Perhaps that docker registry has been deprecated?

https://github.com/TykTechnologies/tyk-gateway-docker/blob/85b898f625707c05b57e26745e2810f58e0d2743/docker-compose.yml#L4

I got it to work with the following tag:

```yaml
image: tykio/tyk-gateway:v4.1.0
```

**Comment by andrsGutirrz** [comment]
I solve it by changing the image
```yaml
image: tykio/tyk-gateway
```
<img width="1097" alt="image" src="https://user-images.githubusercontent.com/16330583/193501483-64c5bf4b-6f6f-40d3-86a1-fa7f0043ea1d.png">

**Comment by buger** [comment]
Hello! We had an issue with docker hosting, which is fixed now. Thanks for reporting!
