### ISSUE TITLE
Reduced docker image size

### ISSUE THREAD

**Issue by jnpr-muthusk** [TykTechnologies/tyk-gateway-docker#7]
Wondering if tyk gateway container images be built from scratch image than ubuntu ?
If not cleaning up after installation does reduce the size from 1.5 GB to 830 MB.  
One may want to check up the functionality.

FROM ubuntu:14.04
RUN apt-get update &&  apt-get install -y wget curl ca-certificates apt-transport-https curl && apt-get clean && apt-get autoremove
RUN curl https://packagecloud.io/gpg.key | apt-key add - && apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10 && apt-get update && apt-get install -y ca-certificates && apt-get install -y wget build-essential libluajit-5.1-2 luarocks lua-cjson python3-setuptools python3-dev libpython3.4  python3-pip && apt-get clean && apt-get autoremove
RUN wget https://github.com/google/protobuf/releases/download/v3.1.0/protobuf-python-3.1.0.tar.gz &&  tar -xvzf protobuf-python-3.1.0.tar.gz && cd protobuf-3.1.0/ &&  ./configure -prefix=/usr && make && make install && cd python && python3 setup.py build --cpp_implementation && python3 setup.py install --cpp_implementation &&  pip3 install grpcio && rm -fr /protobuf-3.1.0 /protobuf-python-3.1.0.tar.gz
RUN echo "deb https://packagecloud.io/tyk/tyk-gateway/ubuntu/ trusty main" | sudo tee /etc/apt/sources.list.d/tyk_tyk-gateway.list && echo "deb-src https://packagecloud.io/tyk/tyk-gateway/ubuntu/ trusty main" | sudo tee -a /etc/apt/sources.list.d/tyk_tyk-gateway.list && apt-get update &&  apt-get install -y tyk-gateway=2.3.1.2  && apt-get clean  && apt-get autoremove

COPY ./tyk.standalone.conf /opt/tyk-gateway/tyk.conf
VOLUME ["/opt/tyk-gateway/"]

WORKDIR /opt/tyk-gateway
COPY entrypoint.sh /opt/tyk-gateway/entrypoint.sh

CMD ["./entrypoint.sh"]
EXPOSE 8080

**Comment by lonelycode** [comment]
This is great - I think we need to optimise these images for size, we can definitely include this as a development goal.

**Comment by mvdan** [comment]
Another optimization is `--no-install-recommends`, as Debian-like distros love to install optional dependencies that aren't actually useful.
